%%{
  init: {
    'theme': 'dark'
  }
}%%
classDiagram
    class GameObject {
        # Texture2D texture
        # Vector2 vector
        + float X
        + float Y
        + float Width
        + float Height
        + GameObject(Texture2D Texture, float X, float Y)
        + void Draw(spriteBatch: SpriteBatch)
    }

    class MovingObject {
        <<abstract>>
        # Vector2 speed
        # MovingObject(Texture2D texture, float X, float Y, float speedX, float speedY)
    }

    class PhysicalObject {
        + bool IsAlive
        + PhysicalObject(Texture2D texture, float X. float Y, float speedX, float speedY)
        + isAlive
    }

    class GoldCoin {
    }

    class Player {
    }

    class Bullet {
    }

    class Enemy {
    }

    class Mine {
    }

    class Tripod {
    }
%% Ager arvet, Car ärver av Vehicle
    GameObject <|-- MovingObject
    MovingObject <|-- PhysicalObject
    PhysicalObject <|--  GoldCoin 
    PhysicalObject <|--  Player 
    PhysicalObject <|--  Bullet 
    PhysicalObject <|--  Enemy 
    Enemy <|-- Mine
    Enemy <|-- Tripod
    
